### ISSUE TITLE
Question about surfel rendering

### ISSUE THREAD

**Issue by Gatsby23** [RMonica/surfel_next_best_view#1]
Sorry for bothering you. I'm a fresh man to the surfel rendering topics. I really want to know what is the surfel rendering but don't know how to start it. Could you please provide some studying document to help me understand the pipeline of surfeling rendering?

**Comment by RMonica** [comment]
Hi.

Maybe you can study the example in this repository:
https://github.com/sebastianlipponer/surface_splatting
There are also a few references at the end of the README.

I recall another approach which renders triangles and then crops them into circles in the fragment shader, but I cannot find the source code online anymore.

**Comment by Gatsby23** [comment]
> Hi.
> 
> Maybe you can study the example in this repository: https://github.com/sebastianlipponer/surface_splatting There are also a few references at the end of the README.
> 
> I recall another approach which renders triangles and then crops them into circles in the fragment shader, but I cannot find the source code online anymore.

Sorry for replay late. It's really help me a lot, thank you very much
